backend:
  name: github
  branch: main
  repo: d1sc0/updownpod

media_folder: 'src/assets'
publish_mode: editorial_workflow

collections:
  - name: 'episodes'
    label: 'Episodes'
    folder: 'src/content/episodes'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'yaml-frontmatter'
    media_folder_relative: true
    sortable_fields: ['title', 'pubDate']
    default_sort:
      - { field: pubDate, direction: descending }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Date', name: 'pubDate', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Audio URL', name: 'mp3', widget: 'string' }
      - { label: 'Audio Title', name: 'mp3title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'src/content/pages'
    create: false
    slug: '{{slug}}'
    extension: 'md'
    format: 'yaml-frontmatter'
    media_folder_relative: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'navigation'
    label: 'Main Site Menu'
    files:
      - file: 'src/content/navigation.yaml'
        label: 'Main Site Menu'
        name: 'main_menu'
        fields:
          - label: 'Links'
            name: 'links'
            widget: 'list'
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
  - name: 'footer_socials'
    label: 'Footer Socials'
    files:
      - file: 'src/content/footer-links.yaml'
        label: 'Footer Social Links'
        name: 'footer_links'
        fields:
          - label: 'Links'
            name: 'links'
            widget: 'list'
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
              - { label: 'Icon', name: 'icon', widget: 'string' }
              - { label: 'Aria Label', name: 'aria', widget: 'string' }
# Sveltia CMS configuration file
# See: https://github.com/sveltia/cms for documentation and options
